import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Menu from "@/components/header/menu";
import {useEffect, useState} from "react";
import axios from "axios";
import Cards from "@/components/Cards/Cards";
import CapHome from "@/components/home/capHome";
import Footer from "@/components/footer/footer";

const inter = Inter({subsets: ['latin']})

// @ts-ignore
export default function Sold({doma}) {


    return (
        <>
            <Head>
                <title>Проданные</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Menu/>
            <main>
                <CapHome/>
                {doma.length ? (
                    <Cards cards={doma}/>
                ) : (
                    <section>
                        <h1>подождите, загружаем</h1>
                    </section>
                )}
            </main>
            <Footer/>
        </>
    )
}

export async function getServerSideProps() {
    try {
        const {data: doma} = await axios.get('https://1caravan.ru/wp-json/api/v2/doma/sold')
        return {
            props: {doma}, // will be passed to the page component as props
        }
    } catch (error) {
        console.error('Error fetching sold data:', error)
        return {
            props: {doma: []}, // Return empty array on error
        }
    }
}